#!/usr/bin/python3
"""module that prints a matrix of same size"""

def matrix_divided(matrix, div):
    matrix = [[]]
    
    if matrix is not type(int) or  matrix is not type(float):
#        raise TypeError("matrix must be a matrix (list of lists) of integers/floats")
        
        if matrix != matrix:
            raise TypeError("Each row of the matrix must have the same size")
    if div is not type(int) or div is not type(float):
        raise TypeError("div must be a number")
    if div == 0:
        raise ZeroDivisionError("division by zero")
    else:
        new_matrix = matrix / div
        return new_matrix
